# Generated by Django 5.1.3 on 2024-11-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='12423', max_length=15),
            preserve_default=False,
        ),
    ]
