# Generated by Django 5.1.3 on 2024-11-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_image'),
    ]

    operations = [
    ]
