# Generated by Django 5.1.3 on 2024-11-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
